### PR TITLE
Add to README, suppress debug message 

### PR DESCRIPTION
**Pull request by chien**

### CODE REVIEW

**Comment by mull** [comment]
Hey @chien, thanks for the PR!

I haven't used this gem myself in over two years now, so I can't say I remember much about the codebase. However, I do have some points:

1. .ruby-version and .ruby-gemset should not be in the repository
2. the `pry` is kind of okay but not in any way a requirement, thus I think it shouldn't be in the Gemfile

If you anticipate wanting to build on this gem please let me know, I'll happily transfer ownership.

**Comment by mull** [comment]
Oh and sorry for the incredibly late answer. I'm living without internet at the moment.

**Comment by chien** [comment]
@mull we're actively using scraping hub and their api and would love to contribute what we currently have. That'd be great if you could transfer the ownership. and thanks for the comment. I'll make the changes.

**Comment by mull** [comment]
@chien can you give me the details as to whom I should transfer ownership to?

**Comment by abevoelker** [comment]
If you aren't interested in the gem namespace anymore and @chien doesn't want it, I'd gladly take it

**Comment by chien** [comment]
@mull to @chien is fine. @abevoelker, happy to co-maintain it :)

**Comment by abevoelker** [comment]
@chien Nah that's okay, I'm taking a slightly different direction in implementation so I'll just pick a different gem name :smile_cat: Cheers

**Comment by chien** [comment]
@mull Sorry for the late response. Can you please transfer the ownership to RetSKU-development Thanks a lot.

**Comment by chien** [comment]
@mull can you merge/release or transfer the ownership? Would love to release the gem so that we don't need to use the repo. Thanks.

**Comment by mull** [comment]
@chien sorry for the delay. Seems like you need to delete your current repo for me to transfer this one to you.

**Comment by mull** [comment]
@chien but of course transferring the rubygems ownership would just be enough.. :) You need to give me your email though.

**Comment by chien** [comment]
@mull Can you please transfer the ownership to  RetSKU-development ?
And my email is chien.cc.kuo@gmail.com 

Thanks a lot. :)

**Comment by mull** [comment]
@chien I need your rubygems email 🙈 

I'll just change this repo with a link to yours once ownership is transferred, I can't transfer to your org without admin rights anyhow. :)

**Comment by chien** [comment]
Can you transfer to the repo to my account? chien

and the email for Rubygem is chien.cc.kuo@gmail.com and my rubygem account handle is chien.

Thanks a lot for the help.

**Comment by mull** [comment]
Everything transferred (supposedly.) Thanks for taking it!

**Pull request merged**
